### ISSUE TITLE
Problema con los backends de autenticación

### ISSUE THREAD

**Issue by Pabalvcar** [Villanueva-del-Trabuco-EGC/decide#11]
Hola, estaba añadiendo funcionalidades al sistema y me he dado cuenta que el login del admin de django no me funcionaba al iniciar sesion con el usuario admin pabalvcar, y he llegado a la conclusion de que esto es porque existe otro usuario llamado Pabalvcar. Creo que el problema se debe a que django está intentando verificar primero con el backend de autenticación que ha introducido @javmarjae. ¿Habría algún problema si cambio el orden de los backends para que primero pruebe el estándar de Django?

**Comment by javmarjae** [comment]
Buenas @Pabalvcar , en caso de que no te funcione por tener dos usuarios con el mismo nombre, puede ser problema del backend. Te recomiendo poner el backend default de Django en primer lugar en settings.py y luego el personalizado. Después de eso no te dará error por usuario duplicado, y te dejará iniciar sesión con el gmail del usuario que quieras. Saludos.

**Comment by Pabalvcar** [comment]
Lo he probado y ese era el problema. Solucionado, muchas gracias.
