### ISSUE TITLE
GitHub Actions fallan despues de fusionar con global

### ISSUE THREAD

**Issue by TheNeoStormZ** [Villanueva-del-Trabuco-EGC/decide#16]
Da un error a la hora de realizar el migrate.py, debido a que le falta una relación:

psycopg2.errors.UndefinedTable: relation "auth_user" does not exist

Os ha pasado @Villanueva-del-Trabuco-EGC/villanueva-del-trabuco-2 ?

**Comment by TheNeoStormZ** [comment]
Como solución temporal se ha borrado de los actions las migraciones, debido a que fallaban en ese paso y ademas estaban marcadas como innecesarias. Dejo la issue abierta unos dias mas por si alguien tiene una forma mejor de arreglarlo

**Comment by TheNeoStormZ** [comment]
Arreglado después de fusionar con https://github.com/Villanueva-del-Trabuco-EGC/decide/pull/20

**Comment by plss12** [comment]
A priori ya funcionan correctamente
