### ISSUE TITLE
Despliegue de la aplicación

### ISSUE THREAD

**Issue by Pabalvcar** [Villanueva-del-Trabuco-EGC/decide#21]
Hola, necesitaría que la aplicación se encuentre desplegada en PythonAnywhere o una plataforma similar cuanto antes posible, ya que antes de añadir más redes sociales me gustaria comprobar el correcto funcionamiento de las mismas una vez desplegado el sistema. Si lo hacemos más tarde, arriesgamos un posible fallo en la tarea. No digo que yo no pueda realizar el despliegue, y estoy dispuesto a llevar a cabo el proceso pero necesitaría ayuda en cualquier caso debido a mi inexperiencia con este tipo de plataformas.

**Comment by plss12** [comment]
Hola, tengo algo de práctica en PythonAnyWhere, podría ayudarte cuando necesites.
