### ISSUE TITLE
Traducciones para realizar tests de Selenium

### ISSUE THREAD

**Issue by alvmorcal1** [Villanueva-del-Trabuco-EGC/decide#26]
Necesito que aquellas traducciones relativas al html visualizer, las cuales se encuentran en la rama develop, se añadan a la rama master para poder sincronizar el fork de decide-part-2 y así realizar tests con selenium, que dependen de estas traducciones.

**Comment by TheNeoStormZ** [comment]
No es necesario tener todo en master para poder sincronizar con el repo de tu grupo; unicamente tienes que crear una pull desde develop hacia el master de tu repo.

**Comment by alvmorcal1** [comment]
Se han conseguido realizar los tests sin necesidad de depender finalmente de estas traducciones, procedo a cerrar issue.
