### ISSUE TITLE
Duda con GitHub

### ISSUE THREAD

**Issue by Pabalvcar** [Villanueva-del-Trabuco-EGC/decide#8]
Hola, tengo un problema con GitHub, quiero actualizar mi rama con la rama master del repositorio para tener todos los cambios introducidos recientemente, sin abrir un pull request. ¿Alguien sabría como hacerlo? ¿Debo hacer un rebase?

**Comment by Dr-Vell** [comment]
1 -> git checkout auth-social/pabalvcar
2 -> git merge origin/master

**Comment by Dr-Vell** [comment]
Esos dos comandos deberían actualizar tu rama con los cambios de master

**Comment by TheNeoStormZ** [comment]
Tambien recomiendo el uso de GitHub Desktop en caso de duda, para no provocar errores innecesarios

**Comment by Pabalvcar** [comment]
Vale, gracias a los dos.
